DEV/src/objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Sessions__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Speaker__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{0000}</displayFormat>
        <label>Session Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DEV/src/objects/Sessions__c.object
<CustomObject>
    <description>to maintains information about sessions</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Select the level of Topic</inlineHelpText>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Beginner</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session_date__c</fullName>
        <label>Session date</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DEV/src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DEV/src/classes/sendconfirmationmail_test.cls
@isTest
public class sendconfirmationmail_test {
    
  static testmethod void testconfirmationmail()
  {
      
      Sessions__c ses = new Sessions__c();
      ses.Name = 'Testing trigger';
      ses.Description__c = 'Used for code covarege ';
      ses.Level__c='Advanced';
      ses.Session_date__c = system.now();
      
      insert ses;
      
      Speaker__c sep = new Speaker__c();
      sep.Last_Name__c = 'Test';
      sep.Status__c ='Active';
      sep.Email__c = 'xyz@gmail.com';
      
      insert sep;
      
      
      Session_Speaker__c ss = new Session_Speaker__c();
      ss.Session__c = ses.id;
      ss.Speaker__c = sep.id;
      
      insert ss;
  }

    static testmethod void testconfirmationmail2()
  {
      
      Sessions__c ses1 = new Sessions__c();
      ses1.Name = 'Testing trigger1';
      ses1.Description__c = 'Used for code covarege1 ';
      ses1.Level__c='Advanced';
      ses1.Session_date__c = system.now();
      
      insert ses1;
      
      Sessions__c ses2 = new Sessions__c();
      ses2.Name = 'Testing trigger1';
      ses2.Description__c = 'Used for code covarege1 ';
      ses2.Level__c='Advanced';
      ses2.Session_date__c = system.now();
      
      insert ses2;
      
      Speaker__c sep1 = new Speaker__c();
      sep1.Last_Name__c = 'Test2';
      sep1.Status__c ='Active';
      sep1.Email__c = 'xyzabc@gmail.com';
      
      insert sep1;
      
      
      Session_Speaker__c ss1 = new Session_Speaker__c();
      ss1.Session__c = ses1.id;
      ss1.Speaker__c = sep1.id;
      
      insert ss1;
      
      Session_Speaker__c ss2 = new Session_Speaker__c();
      ss2.Session__c = ses2.id;
      ss2.Speaker__c = sep1.id;
      
      insert ss2;
      
  }

    
    
    
}