DEV/src/objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Sessions__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Speaker__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{0000}</displayFormat>
        <label>Session Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DEV/src/objects/Sessions__c.object
<CustomObject>
    <description>to maintains information about sessions</description>
    <label>Session</label>
    <nameField>
        <label>Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DEV/src/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DEV/src/classes/getsessspeakers.cls
public class getsessspeakers {
    string ids{get;set;}
    public list<Session_Speaker__c> sesspeak{get;set;}

    public getsessspeakers()
    {
      ids = ApexPages.currentPage().getParameters().get('ids') ;
        system.debug('------ids------'+ids);
        list<string> allids = new list<string>();
        allids = ids.split(',');
        system.debug(allids.size()+'-----after split---------'+allids);
        list<Sessions__c> ses = [select id,Name from Sessions__c where id=:allids];
        system.debug('---ses---'+ses);
        sesspeak = new list<Session_Speaker__c>();
        sesspeak = [select id,Name,Session__c,Session__r.Name,Speaker__c,Speaker__r.Name from Session_Speaker__c where Session__c =: allids ];
        system.debug(sesspeak.size()+'----sesspeak-----'+sesspeak);
        
        
        
    }
    
}