DEV/src/objects/Sessions__c.object
<CustomObject>
    <description>to maintains information about sessions</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DEV/src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DEV/src/classes/Sessspeaker.cls
public class Sessspeaker {
   public string sesname{get;set;}
    public string sesdescription{get;set;}
    public string Speakerfname{get;set;}
    public string SpeakerEmail{get;set;}
    public string Speakerlname{get;set;}
    public string Speakerstatus{get;set;}
    public string ids;
    public Sessspeaker()
    {
    system.debug('-----constructer called-------');    
    }

    public pagereference save()
    {
       if(String.isEmpty(sesname) && String.isEmpty(sesdescription) && String.isEmpty(Speakerfname) && String.isEmpty(SpeakerEmail) && String.isEmpty(Speakerlname) && String.isEmpty(Speakerstatus) )
       {
       ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please enter all value to continue'));
  
       }else{
           
           Sessions__c ses = new Sessions__c();
           ses.Name = sesname;
           ses.Description__c = sesdescription;
           insert ses;
           ids = string.valueof(ses.id);
           Speaker__c sep = new Speaker__c();
           sep.First_Name__c = Speakerfname;
           sep.Last_Name__c = Speakerlname;
           sep.Email__c = SpeakerEmail;
           sep.Status__c = Speakerstatus;
           insert sep;
           
           if(ses.id!=null && sep.id!=null)
           {
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.info,'Session and Speaker details are successfully created'));   
           }else{
               
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.info,'Faled.Please try later.'));
           }
       }
        
       

        
       PageReference ref = new PageReference('/'+ids);
       ref.setRedirect(true);
       return ref;
    }
       
    
}